/**
 * GET /api/book/download?s=<sessionId>&exp=<unix_ts>&sig=<hmac>
 * Streams the watermarked PDF from R2 after verifying the HMAC-signed link.
 * Links are generated by the watermark Worker after each purchase and are valid
 * for 30 days. After expiry, the file is also removed from R2 by the Worker's
 * scheduled cleanup.
 */
export async function onRequestGet({ request, env }) {
  const url = new URL(request.url);
  const sessionId = url.searchParams.get('s');
  const exp = url.searchParams.get('exp');
  const sig = url.searchParams.get('sig');

  if (!sessionId || !exp || !sig) {
    return new Response('Missing parameters', { status: 400 });
  }

  const expirySec = Number(exp);
  if (!Number.isFinite(expirySec) || Date.now() / 1000 > expirySec) {
    return new Response(
      'This download link has expired. Please contact contact@gridstab.com to request a new one.',
      { status: 410, headers: { 'Content-Type': 'text/plain; charset=utf-8' } }
    );
  }

  const expected = await signDownloadToken(sessionId, expirySec, env.DOWNLOAD_LINK_SECRET);
  if (!timingSafeEqual(sig, expected)) {
    return new Response('Invalid signature', { status: 403 });
  }

  const object = await env.BOOK_BUCKET.get(`delivered/${sessionId}.pdf`);
  if (!object) {
    return new Response(
      'Book not found. Please contact contact@gridstab.com.',
      { status: 404, headers: { 'Content-Type': 'text/plain; charset=utf-8' } }
    );
  }

  return new Response(object.body, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': 'attachment; filename="Grid-Stability-Gilles-Chaspierre.pdf"',
      'Cache-Control': 'private, no-store',
    },
  });
}

async function signDownloadToken(sessionId, expirySec, secret) {
  const encoder = new TextEncoder();
  const key = await crypto.subtle.importKey(
    'raw',
    encoder.encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign']
  );
  const sig = await crypto.subtle.sign('HMAC', key, encoder.encode(`${sessionId}|${expirySec}`));
  return Array.from(new Uint8Array(sig))
    .map(b => b.toString(16).padStart(2, '0'))
    .join('');
}

function timingSafeEqual(a, b) {
  if (a.length !== b.length) return false;
  let result = 0;
  for (let i = 0; i < a.length; i++) {
    result |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return result === 0;
}
